name: Build & Run tests
on:
  push:
    branches: [ testing ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup NodeJS
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Setup backend
        run: |
          cd backend
          npm i
          node server.js &
          cd ..
          
      - name: Setup frontend
        run: |
          cd frontend
          npm i
          npm run dev &
          cd ..

      - name: Cypress tests
        run: |
          cd cypress
          npm i
          npx cypress run
      
          